//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gripper
    {
        public int GripperID { get; set; }
        public string GripperName { get; set; }
        public string Stroke__in_ { get; set; }
        public double Force_ID { get; set; }
        public double Force_OD { get; set; }
        public int Ma { get; set; }
        public int Mb_Mc { get; set; }
        public int Price { get; set; }
    }
}
